---
apiVersion: v1
kind: ReplicationController
metadata:
  name: go-email-parser
spec:
  replicas: 3
  selector:
    app: go-email-parser
  template:
    metadata:
      name: go-email-parser
      labels:
        app: go-email-parser
    spec:
      containers:
      - name: go-email-parser
        env:
        - name: REDIS_HOST
          value: "redis:6379"
        image: go-email-parser:v2
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: go-email-parser
spec:
  selector:
    app: go-email-parser
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
