---
apiVersion: v1
kind: ReplicationController
metadata:
  name: go-email-parser
spec:
  replicas: 3
  selector:
    app: go-email-parser
  template:
    metadata:
      name: go-email-parser
      labels:
        app: go-email-parser
    spec:
      containers:
      - name: go-email-parser
        image: go-email-parser:v1
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: go-email-parser
spec:
  selector:
    app: go-email-parser
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
